version: "3"

services:
  rabbit:
    image: rabbitmq:3.6-management-alpine
    container_name: rabbitmq
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
