# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rservice.proto\"\x06\n\x04Null\"8\n\x12\x41ppointmentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0cservice_code\x18\x02 \x01(\t\"\x1f\n\x0b\x41ppointment\x12\x10\n\x08queue_id\x18\x02 \x01(\t\")\n\rCheckResponse\x12\x18\n\x10response_message\x18\x01 \x01(\t2\xa6\x01\n\x12\x41ppointmentService\x12\x34\n\x0f\x42ookAppointment\x12\x13.AppointmentRequest\x1a\x0c.Appointment\x12(\n\x11\x43\x61ncelAppointment\x12\x0c.Appointment\x1a\x05.Null\x12\x30\n\x10\x43heckAppointment\x12\x0c.Appointment\x1a\x0e.CheckResponseb\x06proto3'
)




_NULL = _descriptor.Descriptor(
  name='Null',
  full_name='Null',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=23,
)


_APPOINTMENTREQUEST = _descriptor.Descriptor(
  name='AppointmentRequest',
  full_name='AppointmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='AppointmentRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service_code', full_name='AppointmentRequest.service_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=81,
)


_APPOINTMENT = _descriptor.Descriptor(
  name='Appointment',
  full_name='Appointment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='queue_id', full_name='Appointment.queue_id', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=114,
)


_CHECKRESPONSE = _descriptor.Descriptor(
  name='CheckResponse',
  full_name='CheckResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_message', full_name='CheckResponse.response_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=157,
)

DESCRIPTOR.message_types_by_name['Null'] = _NULL
DESCRIPTOR.message_types_by_name['AppointmentRequest'] = _APPOINTMENTREQUEST
DESCRIPTOR.message_types_by_name['Appointment'] = _APPOINTMENT
DESCRIPTOR.message_types_by_name['CheckResponse'] = _CHECKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Null = _reflection.GeneratedProtocolMessageType('Null', (_message.Message,), {
  'DESCRIPTOR' : _NULL,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Null)
  })
_sym_db.RegisterMessage(Null)

AppointmentRequest = _reflection.GeneratedProtocolMessageType('AppointmentRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPOINTMENTREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:AppointmentRequest)
  })
_sym_db.RegisterMessage(AppointmentRequest)

Appointment = _reflection.GeneratedProtocolMessageType('Appointment', (_message.Message,), {
  'DESCRIPTOR' : _APPOINTMENT,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Appointment)
  })
_sym_db.RegisterMessage(Appointment)

CheckResponse = _reflection.GeneratedProtocolMessageType('CheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:CheckResponse)
  })
_sym_db.RegisterMessage(CheckResponse)



_APPOINTMENTSERVICE = _descriptor.ServiceDescriptor(
  name='AppointmentService',
  full_name='AppointmentService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=160,
  serialized_end=326,
  methods=[
  _descriptor.MethodDescriptor(
    name='BookAppointment',
    full_name='AppointmentService.BookAppointment',
    index=0,
    containing_service=None,
    input_type=_APPOINTMENTREQUEST,
    output_type=_APPOINTMENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CancelAppointment',
    full_name='AppointmentService.CancelAppointment',
    index=1,
    containing_service=None,
    input_type=_APPOINTMENT,
    output_type=_NULL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckAppointment',
    full_name='AppointmentService.CheckAppointment',
    index=2,
    containing_service=None,
    input_type=_APPOINTMENT,
    output_type=_CHECKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_APPOINTMENTSERVICE)

DESCRIPTOR.services_by_name['AppointmentService'] = _APPOINTMENTSERVICE

# @@protoc_insertion_point(module_scope)
