# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import service_pb2 as service__pb2


class AppointmentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BookAppointment = channel.unary_unary(
                '/AppointmentService/BookAppointment',
                request_serializer=service__pb2.AppointmentRequest.SerializeToString,
                response_deserializer=service__pb2.Appointment.FromString,
                )
        self.CancelAppointment = channel.unary_unary(
                '/AppointmentService/CancelAppointment',
                request_serializer=service__pb2.Appointment.SerializeToString,
                response_deserializer=service__pb2.Null.FromString,
                )
        self.CheckAppointment = channel.unary_unary(
                '/AppointmentService/CheckAppointment',
                request_serializer=service__pb2.Appointment.SerializeToString,
                response_deserializer=service__pb2.CheckResponse.FromString,
                )


class AppointmentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BookAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppointmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BookAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.BookAppointment,
                    request_deserializer=service__pb2.AppointmentRequest.FromString,
                    response_serializer=service__pb2.Appointment.SerializeToString,
            ),
            'CancelAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAppointment,
                    request_deserializer=service__pb2.Appointment.FromString,
                    response_serializer=service__pb2.Null.SerializeToString,
            ),
            'CheckAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAppointment,
                    request_deserializer=service__pb2.Appointment.FromString,
                    response_serializer=service__pb2.CheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AppointmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AppointmentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BookAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AppointmentService/BookAppointment',
            service__pb2.AppointmentRequest.SerializeToString,
            service__pb2.Appointment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AppointmentService/CancelAppointment',
            service__pb2.Appointment.SerializeToString,
            service__pb2.Null.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AppointmentService/CheckAppointment',
            service__pb2.Appointment.SerializeToString,
            service__pb2.CheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
